# Generated by Django 4.1.5 on 2023-01-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
